<?php
/**
 * Idempotent production settings sync. Runs from ops/ inside the app dir,
 * both on deploy (deploy.yml step 7) and manually on the server.
 * NOTE: Laravel Tinker is NOT installed in production, so the old
 * `artisan tinker --execute=...` deploy step silently did nothing. This
 * uses a raw Laravel bootstrap instead.
 */
$appBase = realpath(__DIR__ . '/..');
require $appBase . '/vendor/autoload.php';
$app = require $appBase . '/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Common\Settings\Models\Setting;
use Common\Settings\Themes\CssTheme;

$updates = [
    // Branding: Keekii 900x344 logo pair.
    //
    // The slot names are about the ARTWORK's colour, not the background it is
    // used on, which is the opposite of what it reads like:
    //
    //   branding.logo_dark  -> dark/black artwork -> rendered in LIGHT mode
    //   branding.logo_light -> light/white artwork -> rendered in DARK mode
    //
    // The consumer is `isDarkMode ? branding.logo_light : branding.logo_dark`
    // in common/foundation/resources/client/auth/ui/auth-layout/auth-layout.tsx,
    // and the shipped pair matches it: images/logo-dark.svg is dark ink on
    // transparency, images/logo-light.svg is light ink.
    //
    // An earlier version of this comment read "white for dark bg / black for
    // light bg" while naming them the other way round. Following it would have
    // deployed the files swapped and rendered an invisible logo, so the mapping
    // is spelled out here rather than abbreviated.
    //
    // GEOMETRY: these were 900x382 until this change. That was a 2.356 aspect
    // against the artwork's real 2.616, so the wordmark was letterboxed inside
    // its own frame with ~5% dead margin top and bottom and rendered visibly
    // too small next to a sibling logo of the true height.
    //
    // The logo ships as SVG, not PNG. A raster cannot animate, and the
    // twin-pulse "i"s are part of the mark now, so public/images/logo-*.svg
    // carries the pulse as CSS inside the vector. That also keeps the navbar,
    // the auth pages and the installer on one file instead of a per-surface
    // motion treatment. Both are generated by scripts/build-wordmark-logo.ps1
    // from the pristine wordmarks, so rebuild rather than edit them.
    //
    // Email is the exception and deliberately does not read this setting:
    // resources/views/vendor/mail/html/message.blade.php points at
    // logo-*-static.svg, because mail clients flatten or drop animated SVG and
    // a missing logo in a transactional email is worse than a still one.
    //
    // The artwork itself is the Bricolage Grotesque wordmark, rebuilt from the
    // self-hosted variable font so the lockup matches the display face used
    // everywhere in the app. The supplied files are kept verbatim, C2PA
    // credentials intact, in ops/logo-assets/supplied/ -- they are reference
    // art, not what ships. See ops/logo-assets/supplied/NOTES.md.
    'branding.logo_dark' => 'images/logo-dark.svg',
    'branding.logo_light' => 'images/logo-light.svg',
    'branding.logo_dark_mobile' => 'images/logo-dark.svg',
    'branding.logo_light_mobile' => 'images/logo-light.svg',
    // Direct-stream fallback: absolute yt-dlp binary path
    'youtube.yt_dlp_binary' => '/usr/local/bin/yt-dlp',
    // YouTube embed origin rotation via Piped instances
    'youtube.piped_instances' =>
        'https://pipedapi.kavin.rocks,https://pipedapi.adminforge.de,https://api.piped.private.coffee,https://pipedapi.reallyaweso.me,https://pipedapi.ducks.party,https://pipedapi.orangenet.cc,https://pipedapi-libre.kavin.rocks,https://pipedapi.nosebs.ru,https://pipedapi.leptons.xyz,https://piped-api.privacy.com.de',
    // Jamendo catalog search (royalty-free)
    'jamendo.client_id' => '983a02d9',
    // LRCLIB lyrics integration — make the lyrics UI reachable
    'player.hide_lyrics' => false,
    'player.hide_lyrics_button' => false,
    /*
     * Download button visibility.
     *
     * This is a global frontend gate, not the authorization check:
     * `useDownloadEntitlement` reads `player.enable_download` and returns false
     * immediately when it is off, which hides the button for EVERY user
     * regardless of plan. The seeded default is false (see
     * resources/defaults/default-settings.php), and default-settings.php only
     * ever runs on first install, so flipping the default there would not
     * change an already-installed production database. Hence the override here.
     *
     * Enabling this does NOT hand downloads out for free: the entitlement hook
     * also requires a `music.download`/`music.offline` permission, those
     * permissions are granted only to the Premium products by
     * database/migrations/2026_10_05_120000_realign_plans_and_enable_billing.php,
     * and app/Policies/TrackPolicy.php::download() re-checks server-side on the
     * actual download request. So the switch is only what makes the button
     * *visible* to users the server already allows to download.
     */
    'player.enable_download' => true,
];

$changed = 0;
foreach ($updates as $name => $value) {
    $exists = Setting::where('name', $name)->exists();
    Setting::updateOrCreate(['name' => $name], ['value' => $value]);
    echo '[' . ($exists ? 'updated' : 'added') . "] $name\n";
    $changed++;
}
echo "Processed $changed settings.\n";

/*
 * ---------------------------------------------------------------------------
 * Theme tokens ("Monochrome Ember" — see docs/design-direction.md)
 * ---------------------------------------------------------------------------
 * The rendered theme comes from the `css_themes` table, NOT from
 * config/themes.php: CssThemesTableSeeder only INSERTs a theme when one is
 * missing and never updates an existing row, so editing config alone changes
 * nothing in production. This pushes the config values into the default
 * light/dark rows on every deploy, which makes config/themes.php the single
 * source of truth and the edits reviewable in a diff.
 *
 * Merge, don't replace: anything an admin has customised that is not defined in
 * config/themes.php is preserved, so this can't silently destroy a deliberate
 * per-theme tweak. Tokens explicitly listed in config/themes.php are owned by
 * the config and always win.
 */
$tokenSources = [
    'default_light' => 'light',
    'default_dark' => 'dark',
];

$themesChanged = 0;
foreach ($tokenSources as $flag => $scheme) {
    $theme = CssTheme::where('type', 'site')->where($flag, true)->first();

    if (!$theme) {
        echo "[skipped] no site theme with {$flag} = true\n";
        continue;
    }

    // CssTheme casts `values` <-> JSON via get/setValuesAttribute.
    try {
        $current = $theme->values;
    } catch (\TypeError $e) {
        // Malformed JSON in the column would otherwise fatal the whole deploy.
        echo "[error] theme '{$theme->name}' has malformed values JSON, skipping\n";
        continue;
    }
    $current = is_array($current) ? $current : [];

    $desired = config("themes.{$scheme}");

    if (!is_array($desired) || !$desired) {
        echo "[error] config/themes.php has no '{$scheme}' scheme\n";
        continue;
    }

    $merged = array_merge($current, $desired);

    if ($merged === $current) {
        echo "[unchanged] theme '{$theme->name}' already matches config/themes.php\n";
        continue;
    }

    // $guarded = [] on CssTheme, and setValuesAttribute json_encodes the array.
    $theme->values = $merged;
    $theme->save();

    $count = count(array_diff_assoc($merged, $current));
    echo "[updated] theme '{$theme->name}' ({$scheme}) — {$count} token(s) applied\n";
    $themesChanged++;
}

echo "Processed {$themesChanged} theme(s).\n";

/*
 * ---------------------------------------------------------------------------
 * Landing Page Sync
 * ---------------------------------------------------------------------------
 * The landing page is stored as a JSON string in the settings table.
 * We want to forcibly push our newly engineered AIDA-compliant Keekii
 * landing page design to the production database so the React frontend sees it.
 */
$defaultSettings = require $appBase . '/resources/defaults/default-settings.php';
$landingPageConfig = null;
foreach ($defaultSettings as $setting) {
    if ($setting['name'] === 'landingPage') {
        $landingPageConfig = $setting['value'];
        break;
    }
}

if ($landingPageConfig) {
    Setting::updateOrCreate(['name' => 'landingPage'], ['value' => $landingPageConfig]);
    echo "[updated] landingPage JSON config applied from default-settings.php\n";
}

/*
 * ---------------------------------------------------------------------------
 * Footer Menu (public company / plan / legal links)
 * ---------------------------------------------------------------------------
 * Every menu in the app -- sidebar, mobile, auth dropdown, footer -- is stored
 * inside a SINGLE `menus` row as one JSON blob. That is the trap here: a plain
 * Setting::updateOrCreate on 'menus' would silently discard every menu an
 * admin has ever arranged. So this does not write the `menus` row wholesale.
 *
 * It only ever APPENDS the default footer menu, and only when no menu already
 * claims the 'footer' position. Once an admin edits the footer at
 * /admin/settings/menus this block becomes a no-op, so their arrangement is
 * never reverted by a later deploy.
 *
 * Why this is needed at all: the 'menus' row is created once, on first
 * install. CreateDefaultMenus() in the common package returns early when the
 * row already exists, and the footer seed lives in
 * resources/defaults/default-settings.php -- which therefore has no path to an
 * existing database. Production had Primary/Secondary/Mobile and no 'footer'
 * position, so the seeded links never appeared.
 *
 * The three-column Company / Useful links / Legal nav at the bottom of each
 * public page is NOT handled here. That is hardcoded in
 * resources/client/company/company-site-map.ts and always renders.
 */
$footerMenu = null;
foreach ($defaultSettings as $setting) {
    if ($setting['name'] === 'menus') {
        $footerMenu = collect(json_decode($setting['value'], true))
            ->first(fn ($menu) => in_array('footer', $menu['positions'] ?? [], true));
        break;
    }
}

if (! $footerMenu) {
    echo "[skipped] no default menu declares the 'footer' position\n";
} else {
    $menusRow = Setting::where('name', 'menus')->first();
    $menus = $menusRow ? ($menusRow->value ?? []) : [];
    $menus = is_array($menus) ? $menus : (json_decode($menus, true) ?: []);

    if (! is_array($menus)) {
        // Refuse to guess: overwriting a row we failed to parse could destroy
        // every menu in the app. Leave it for a human to inspect.
        echo "[error] 'menus' row is not valid JSON; refusing to modify it\n";
    } elseif (collect($menus)->contains(fn ($m) => in_array('footer', $m['positions'] ?? [], true))) {
        echo "[skipped] a 'footer' menu already exists; leaving admin edits intact\n";
    } else {
        $menus[] = $footerMenu;
        Setting::updateOrCreate(['name' => 'menus'], ['value' => json_encode($menus)]);
        echo '[updated] appended default Footer menu ('
            . count($footerMenu['items'] ?? []) . " items) to 'menus'\n";
    }
}

/*
 * ---------------------------------------------------------------------------
 * Cookie Notice (GDPR)
 * ---------------------------------------------------------------------------
 * Same trap as the footer menu above, for the same reason: default-settings.php
 * only reaches a database on first install, because InsertDefaultSettings()
 * skips every setting name that already exists. Production was installed long
 * before the cookie notice was switched on, so 'cookie_notice.enable' already
 * exists there as 'false' and editing the default would have no effect.
 *
 * Unlike the footer menu this DOES overwrite an existing value, because the
 * notice is a legal control: an admin who has toggled it is either mid-testing
 * or has deliberately opted out, and a deploy silently reversing that would be
 * worse than a stale default. To opt out for good, set COOKIE_NOTICE_ENABLE=0
 * in the deploy environment.
 *
 * The information button is only written when it is missing entirely, so an
 * admin's chosen label and destination are never overwritten.
 */
$cookieNoticeEnabled = getenv('COOKIE_NOTICE_ENABLE') !== '0';

Setting::updateOrCreate(['name' => 'cookie_notice.enable'], ['value' => $cookieNoticeEnabled]);
Setting::updateOrCreate(['name' => 'cookie_notice.position'], ['value' => 'bottom']);

if (! Setting::where('name', 'cookie_notice.button')->exists()) {
    foreach ($defaultSettings as $setting) {
        if ($setting['name'] !== 'cookie_notice.button') {
            continue;
        }

        // Passed through as an array on purpose: 'cookie_notice.button' is in
        // Settings::$jsonKeys, so the model encodes it and decodes it back to
        // an array for the client.
        $button = is_string($setting['value'])
            ? json_decode($setting['value'], true)
            : $setting['value'];

        Setting::updateOrCreate(['name' => 'cookie_notice.button'], ['value' => $button]);
        echo "[updated] cookie notice info button seeded (points to /cookies)\n";
        break;
    }
}

echo '[updated] cookie_notice.enable=' . var_export($cookieNoticeEnabled, true)
    . ", position=bottom\n";

/*
 * ---------------------------------------------------------------------------
 * Geo Homepage Enabler
 * ---------------------------------------------------------------------------
 * The per-country homepage swap (ResolveGeoHomepage) only engages when the
 * site homepage is a channel and homepage.geo_countries maps ISO2 -> channel
 * id. `artisan channels:country` creates the country channels and writes that
 * map on every deploy, so by the time this script runs the map is present and
 * we can safely switch the homepage type to "channel".
 *
 * The default value is resolved against the DB (preferring the seeded
 * discovery/homepage channel) rather than hardcoded, because channel ids are
 * not stable across environments. If no suitable channel exists the homepage
 * is left untouched and an admin can pick one in Settings > General.
 */
use App\Models\Channel;

$geoMapRaw = settings('homepage.geo_countries');
$geoMap = $geoMapRaw ? json_decode($geoMapRaw, true) : [];

if (!is_array($geoMap) || $geoMap === []) {
    echo "[skipped] geo homepage not enabled: homepage.geo_countries is empty\n";
} else {
    $defaultChannel = Channel::whereIn('slug', ['discover', 'homepage'])
        ->orderBy('id')
        ->first()
        ?: Channel::where('type', 'channel')
            ->where('public', true)
            ->orderBy('id')
            ->first();

    if (!$defaultChannel) {
        echo "[error] geo homepage enabled but no default channel exists; leave homepage as-is\n";
    } else {
        Setting::updateOrCreate(['name' => 'homepage.type'], ['value' => 'channel']);
        Setting::updateOrCreate(
            ['name' => 'homepage.value'],
            ['value' => (int) $defaultChannel->id],
        );
        echo '[updated] homepage.type=channel, homepage.value=' . $defaultChannel->id
            . ' (' . $defaultChannel->slug . ') [' . count($geoMap) . " countries mapped]\n";
    }
}
